name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@main
        with:
          USERNAME: itsam-13

      - name: Commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "generate 3d graph"
          git push
